### ISSUE TITLE
License about using this mod

### ISSUE THREAD

**Issue by XenonDB** [EyeDeck/IDEK-Mixin-Tweaks#1]
Hi,
Since Reika haven't update Chromaticraft for a long time, I want to submit this mod as an approved Non-CurseForge mod to use it in my modpack until Reika fix this bug.
However it seems there's no explicit license for this mod so will be considered all right reserved.

Can this mod be used in other public pack?
If yes, maybe you can provide a license for this project.

Note: [This](https://support.curseforge.com/en/support/solutions/articles/9000197908-exporting-a-modpack-for-curseforge-project-submission#Third-Party-Mods) is how to submit a request for approving Non-CurseForge mods used in pack.

**Comment by EyeDeck** [comment]
Done.
